-- Create musics table
CREATE TABLE musics (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    name TEXT NOT NULL,
    artist TEXT NOT NULL,
    CONSTRAINT unique_music_artist UNIQUE(name, artist)
);

-- Create index for faster lookups
CREATE INDEX idx_musics_name_artist ON musics(name, artist);
CREATE INDEX idx_musics_artist ON musics(artist);

-- Create playlists table
CREATE TABLE playlists (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    num_tracks INT,
    musics INT[]
);

-- Create index for playlist music arrays
CREATE INDEX idx_playlists_musics ON playlists USING GIN(musics);
